cd ./Generic-Repositories/big-list-of-naughty-strings && git pull && cd ..
cd ./Generic-Repositories/fuzzdb && git pull && cd ..
cd ./Generic-Repositories/payloads && git pull && cd ..
cd ./Generic-Repositories/PayloadsAllTheThings && git pull && cd ..
cd ./Generic-Repositories/RobotsDisallowed && git pull && cd ..
cd ./Generic-Repositories/SecLists && git pull && cd ..
cd ./Generic-Repositories/wfuzz && git pull && cd ..
cd ./Mass-Targetting/AutoSploit && git pull && cd ..
cd ./Mass-Targetting/pocsuite3 && git pull && cd ..
cd ./Mass-Targetting/V3n0M-Scanner && git pull && cd ..
cd ./WebAppTools/API/API-fuzzer && git pull && cd ..
cd ./WebAppTools/API/Astra && git pull && cd ..
cd ./WebAppTools/Enumeration/gobuster && git pull && cd ..
cd ./WebAppTools/Git-Tools/git-dumper && git pull && cd ..
cd ./WebAppTools/Git-Tools/git-scanner && git pull && cd ..
cd ./WebAppTools/Git-Tools/GitTools && git pull && cd ..
cd ./WebAppTools/GraphQL/clairvoyance && git pull && cd ..
cd ./WebAppTools/GraphQL/GraphCrawler && git pull && cd ..
cd ./WebAppTools/GraphQL/graphinder && git pull && cd ..
cd ./WebAppTools/GraphQL/graphw00f && git pull && cd ..
cd ./WebAppTools/GraphQL/NoSQLMap && git pull && cd ..
cd ./WebAppTools/GraphQL/shapeshifter && git pull && cd ..
cd ./WebAppTools/Image-Manipulation/imgjs_polygloter && git pull && cd ..
cd ./WebAppTools/Injection/commix && git pull && cd ..
cd ./WebAppTools/Injection/GraphQLmap && git pull && cd ..
cd ./WebAppTools/Injection/liffy && git pull && cd ..
cd ./WebAppTools/Injection/NoSQLMap && git pull && cd ..
cd ./WebAppTools/Injection/sqlmap && git pull && cd ..
cd ./WebAppTools/Injection/SSRFmap && git pull && cd ..
cd ./WebAppTools/Injection/SSTImap && git pull && cd ..
cd ./WebAppTools/Injection/tplmap && git pull && cd ..
cd ./WebAppTools/Injection/ysomap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Enumeration/gobuster && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Git-Tools/git-dumper && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Git-Tools/git-scanner && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Git-Tools/GitTools && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/GraphQL/clairvoyance && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/GraphQL/GraphCrawler && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/GraphQL/graphinder && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/GraphQL/graphw00f && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/GraphQL/NoSQLMap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/GraphQL/shapeshifter && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Image-Manipulation/imgjs_polygloter && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/commix && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/GraphQLmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/liffy && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/NoSQLMap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/sqlmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/SSRFmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/SSTImap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/tplmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Injection/ysomap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/phpggc && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Shells/Awsome-shells && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Shells/Generic/PyShell && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Shells/PHP/bantam && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Shells/PHP/p0wny-shell && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/Shells/PHP/weevely3 && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Enumeration/gobuster && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Git-Tools/git-dumper && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Git-Tools/git-scanner && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Git-Tools/GitTools && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/GraphQL/clairvoyance && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/GraphQL/GraphCrawler && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/GraphQL/graphinder && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/GraphQL/graphw00f && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/GraphQL/NoSQLMap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/GraphQL/shapeshifter && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Image-Manipulation/imgjs_polygloter && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/commix && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/GraphQLmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/liffy && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/NoSQLMap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/sqlmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/SSRFmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/SSTImap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/tplmap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Injection/ysomap && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Shells/Awsome-shells && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Shells/Generic/PyShell && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Shells/PHP/bantam && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Shells/PHP/p0wny-shell && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/Shells/PHP/weevely3 && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/SrcCodeAudit/Java/spotbugs && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/SrcCodeAudit/Javascript/njsscan && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/SrcCodeAudit/PHP/progpilot && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SOAP/SrcCodeAudit/SAST/graudit && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SrcCodeAudit/Java/spotbugs && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SrcCodeAudit/Javascript/njsscan && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SrcCodeAudit/PHP/progpilot && git pull && cd ..
cd ./WebAppTools/PHP-Exploitation/SrcCodeAudit/SAST/graudit && git pull && cd ..
cd ./WebAppTools/Shells/Awsome-shells && git pull && cd ..
cd ./WebAppTools/Shells/Generic/PyShell && git pull && cd ..
cd ./WebAppTools/Shells/PHP/bantam && git pull && cd ..
cd ./WebAppTools/Shells/PHP/p0wny-shell && git pull && cd ..
cd ./WebAppTools/Shells/PHP/weevely3 && git pull && cd ..
cd ./WebAppTools/SrcCodeAudit/Java/spotbugs && git pull && cd ..
cd ./WebAppTools/SrcCodeAudit/Javascript/njsscan && git pull && cd ..
cd ./WebAppTools/SrcCodeAudit/PHP/progpilot && git pull && cd ..
cd ./WebAppTools/SrcCodeAudit/SAST/graudit && git pull && cd ..
cd ./WebAppTools/XSS/dalfox && git pull && cd ..
cd ./WebAppTools/XSS/XSStrike && git pull && cd ..
